-- 004: Seed personas
-- 20 personas across 4 Jabodetabek cities

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('gs_001', 'gading-serpong', 'Vania Adisti', 22, '18-24', 'female', 'Mahasiswi UMN, Lifestyle Content Creator', 'upper-mid', 6500000, 2500000, '["aesthetic","kafe hopping","TikTok trends","pencari promo kartu"]', 'Apartemen area Scientia, Gading Serpong', '{"priceElasticity":"moderate","decisionFactor":["estetika","viral potential","rasa","packaging"],"preferredChannel":["offline (untuk konten)","GoFood"],"weeklyFnBSpend":600000}', '{"values":["ekspresi diri","status sosial","tren"],"mediaConsumption":["TikTok","Instagram","Pinterest"],"peerInfluence":"high"}', '{"culturalNote":"Anak muda Gading Serpong sangat mementingkan visual dan ''vibe'' tempat","competitorAwareness":["Kopi Kenangan","Artisan Coffee Shops","Matcha Bar","Mixue"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('gs_002', 'gading-serpong', 'Aditya Pratama', 27, '25-30', 'male', 'Account Manager di Creative Agency', 'mid', 8500000, 2500000, '["produktif","work from cafe","gym enthusiast","sneakerhead"]', 'Kost Exclusive area Paramount, Gading Serpong', '{"priceElasticity":"moderate","decisionFactor":["kecepatan","lokasi","kualitas bahan","brand"],"preferredChannel":["offline","GrabFood"],"weeklyFnBSpend":800000}', '{"values":["efisiensi","kualitas hidup","networking"],"mediaConsumption":["YouTube","Instagram","LinkedIn"],"peerInfluence":"medium"}', '{"culturalNote":"Daya beli Gading Serpong sangat stabil di akhir pekan","competitorAwareness":["Starbucks","Fore Coffee","Common Grounds"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('gs_003', 'gading-serpong', 'Siska Monica', 34, '31-40', 'female', 'Ibu Rumah Tangga (Mid-High)', 'high', 35000000, 10000000, '["family brunch","healthy eating","shopee platinum","yoga"]', 'Cluster perumahan Foresta, Gading Serpong', '{"priceElasticity":"insensitive","decisionFactor":["kebersihan","halal/sehat","penerimaan anak","brand"],"preferredChannel":["offline (Mall/Ruko)","Delivery"],"weeklyFnBSpend":1500000}', '{"values":["keluarga","kesehatan","pencitraan"],"mediaConsumption":["Instagram","WhatsApp Groups","YouTube Kids (shared)"],"peerInfluence":"high"}', '{"culturalNote":"Target ruko Gading Serpong seringkali adalah keluarga di pagi-siang hari","competitorAwareness":["Bakerzin","Union","Resto Keluarga Premium"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('gs_004', 'gading-serpong', 'Rendy Wijaya', 38, '31-40', 'male', 'Pemilik Toko Olahraga', 'upper-mid', 18000000, 5000000, '["golf","networking","practical","suka makanan berat"]', 'Rumah di area Summarecon', '{"priceElasticity":"moderate","decisionFactor":["porsi","rasa","kenyamanan parkir"],"preferredChannel":["offline","GoFood"],"weeklyFnBSpend":1200000}', '{"values":["bisnis","tradisi","kepraktisan"],"mediaConsumption":["Berita Online","WhatsApp","Facebook"],"peerInfluence":"low"}', '{"culturalNote":"Parkir yang susah di Gading Serpong bisa jadi dealbreaker","competitorAwareness":["Nasi Campur","Bakmi Lokal","Resto Padang Premium"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('gs_005', 'gading-serpong', 'Maya Sari', 24, '18-24', 'female', 'Admin E-commerce', 'lower-mid', 5500000, 1500000, '["pecinta promo","nonton drakor","iseng cobain jajanan"]', 'Kos dekat ruko-ruko', '{"priceElasticity":"sensitive","decisionFactor":["harga promo","viral","rasa manis"],"preferredChannel":["GoFood","ShopeeFood"],"weeklyFnBSpend":400000}', '{"values":["self-reward","hiburan","hemat"],"mediaConsumption":["TikTok","Twitter","Shopee"],"peerInfluence":"high"}', '{"culturalNote":"Sangat sensitif terhadap promo ''Buy 1 Get 1''","competitorAwareness":["Haus!","Menantea","Es Teh Desa"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bsd_001', 'bsd', 'Kevin Jonathan', 26, '25-30', 'male', 'Software Engineer di Tech Giant BSD', 'high', 18000000, 7000000, '["tech-savvy","digital nomad","specialty coffee","gadget"]', 'Apartemen Saveria, BSD', '{"priceElasticity":"insensitive","decisionFactor":["kualitas kopi","kenyamanan WiFi","pembayaran digital"],"preferredChannel":["offline (untuk ngoding)","GrabFood"],"weeklyFnBSpend":1200000}', '{"values":["inovasi","efisiensi","kualitas"],"mediaConsumption":["TechCrunch","YouTube","Twitter/X"],"peerInfluence":"low"}', '{"culturalNote":"BSD adalah hub teknologi, kecepatan dan tech-integration sangat dihargai","competitorAwareness":["Starbucks","Tuku","Ombe Kofie"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bsd_002', 'bsd', 'Fitriani Amin', 32, '31-40', 'female', 'Dosen di Universitas Internasional', 'upper-mid', 14000000, 5000000, '["intelektual","organik","sustainable","bookworm"]', 'Rumah di The Icon, BSD', '{"priceElasticity":"moderate","decisionFactor":["bahan sehat","tanpa MSG","eco-friendly packaging"],"preferredChannel":["offline","E-commerce"],"weeklyFnBSpend":900000}', '{"values":["integritas","keberlanjutan","kesehatan"],"mediaConsumption":["Podcast","Medium","The Jakarta Post"],"peerInfluence":"medium"}', '{"culturalNote":"BSD market cenderung lebih teredukasi soal kesehatan produk","competitorAwareness":["Burgreens","SaladStop","Re.juve"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bsd_003', 'bsd', 'Rizky Ramadhan', 21, '18-24', 'male', 'Mahasiswa Prasetiya Mulya', 'high', 7000000, 4000000, '["hedon","nongkrong di The Breeze","party","crypto trader"]', 'Kos Premium BSD', '{"priceElasticity":"insensitive","decisionFactor":["prestige","keramaian tempat","brand internasional"],"preferredChannel":["offline","GrabFood"],"weeklyFnBSpend":1500000}', '{"values":["status","kebebasan","kesenangan"],"mediaConsumption":["Instagram","TikTok","Discord"],"peerInfluence":"high"}', '{"culturalNote":"Mahasiswa di BSD seringkali memiliki daya beli setara manajer","competitorAwareness":["Arabica","Social House","Senopati-style cafes"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bsd_004', 'bsd', 'Ibu Linda', 45, '41-55', 'female', 'Pengusaha Catering', 'upper-mid', 25000000, 6000000, '["fokus keluarga","grup pengajian","masak","smart shopper"]', 'Giri Loka, BSD', '{"priceElasticity":"moderate","decisionFactor":["keaslian rasa","kebersihan","porsi keluarga"],"preferredChannel":["offline (Pasar Modern BSD)","WhatsApp"],"weeklyFnBSpend":2000000}', '{"values":["tradisi","kualitas","kejujuran"],"mediaConsumption":["Facebook","WhatsApp","YouTube"],"peerInfluence":"high"}', '{"culturalNote":"Pasar Modern BSD adalah titik kumpul krusial untuk segmen dewasa BSD","competitorAwareness":["Sate Khas Senayan","Dapur Solo","Kedai Lokal Legendaris"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bsd_005', 'bsd', 'Dani Setiawan', 29, '25-30', 'male', 'Creative Director', 'mid', 11000000, 3500000, '["artsy","fotografi","sepeda lipat","minimalis"]', 'Rumah di Cisauk (pinggir BSD)', '{"priceElasticity":"moderate","decisionFactor":["desain tempat","storytelling brand","keunikan menu"],"preferredChannel":["offline","Instagram"],"weeklyFnBSpend":700000}', '{"values":["autentisitas"," kreativitas","minimalis"],"mediaConsumption":["Behance","Instagram","Spotify"],"peerInfluence":"medium"}', '{"culturalNote":"Area Cisauk kini jadi alternatif tempat nongkrong estetik bagi warga BSD","competitorAwareness":["Kedai Kopi Kecil","Artisan Bakery","Local Small Brands"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bt_001', 'bekasi-timur', 'Bambang Sugeng', 42, '41-55', 'male', 'Supervisor Pabrik di Jababeka', 'lower-mid', 7500000, 1800000, '["praktis","sayang keluarga","nongkrong di warung","pencinta motor"]', 'Kompleks perumahan padat di Bekasi Timur', '{"priceElasticity":"very_sensitive","decisionFactor":["porsi banyak","harga murah","rasa mantap","cepat"],"preferredChannel":["offline","Takeaway"],"weeklyFnBSpend":300000}', '{"values":["kerja keras","keluarga","stabilitas"],"mediaConsumption":["Facebook","TV","WhatsApp"],"peerInfluence":"medium"}', '{"culturalNote":"Market Bekasi Timur sangat padat dan menyukai kepraktisan pasca kerja","competitorAwareness":["HokBen","RM Padang","Warung Tenda","Es Teh Solo"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bt_002', 'bekasi-timur', 'Siska Pertiwi', 24, '18-24', 'female', 'Admin Gudang', 'low', 5200000, 1000000, '["frugal","pencinta promo ojol","scroll TikTok","koleksi skincare murah"]', 'Kontrakan area Rawalumbu', '{"priceElasticity":"very_sensitive","decisionFactor":["diskon besar","porsi","viralitas"],"preferredChannel":["ShopeeFood","GrabFood"],"weeklyFnBSpend":250000}', '{"values":["berbagi","hiburan murah","keamanan"],"mediaConsumption":["TikTok","Shopee","Facebook"],"peerInfluence":"high"}', '{"culturalNote":"Bekasi Timur memiliki volume pesanan ojek online yang sangat tinggi","competitorAwareness":["Mie Gacoan","Ayam Sabana","Haus!"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bt_003', 'bekasi-timur', 'Dedi Kusuma', 30, '25-30', 'male', 'Driver Operasional Bank', 'lower-mid', 6000000, 1500000, '["mobile","merokok","ngopi di pangkalan","family man"]', 'Area Bulak Kapal', '{"priceElasticity":"sensitive","decisionFactor":["lokasi strategis","harga merakyat","kenyamanan merokok"],"preferredChannel":["offline","Warung"],"weeklyFnBSpend":350000}', '{"values":["kebersamaan","kejantanan","ketenangan"],"mediaConsumption":["YouTube","WhatsApp","Berita Kriminal/Regional"],"peerInfluence":"medium"}', '{"culturalNote":"Tempat nongkrong di Bekasi Timur harus ramah bagi yang ingin santai lama","competitorAwareness":["Warkop DKI","Kantin Kantor","Gerobakan"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bt_004', 'bekasi-timur', 'Ani Rahmawati', 35, '31-40', 'female', 'Pedagang Online', 'mid', 9000000, 3000000, '["sibuk","multi-tasking","pencari inspirasi bisnis","aktif sosmed"]', 'Duren Jaya, Bekasi', '{"priceElasticity":"moderate","decisionFactor":["penerimaan pasar (tren)","kemudahan beli","rasa"],"preferredChannel":["Instagram","WhatsApp","offline"],"weeklyFnBSpend":500000}', '{"values":["kemandirian","sukses ekonomi","fleksibilitas"],"mediaConsumption":["Instagram","TikTok","Marketplace"],"peerInfluence":"medium"}', '{"culturalNote":"Banyak wirausaha muda di Bekasi Timur yang butuh tempat diskusi santai","competitorAwareness":["Kopi Janji Jiwa","Mixue","Sate Maranggi"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('bt_005', 'bekasi-timur', 'Eko Prasetyo', 20, '18-24', 'male', 'Buruh Pabrik Kontrak', 'low', 4800000, 1500000, '["hobi motor","game online (ML/FF)","nongkrong malam","hemat harian"]', 'Mess karyawan', '{"priceElasticity":"very_sensitive","decisionFactor":["harga","porsi","WiFi gratis"],"preferredChannel":["offline","Warkop"],"weeklyFnBSpend":400000}', '{"values":["persahabatan","hiburan","adrenaline"],"mediaConsumption":["YouTube Gaming","TikTok","Facebook Groups"],"peerInfluence":"high"}', '{"culturalNote":"Segmen buruh muda Bekasi mencari tempat hiburan murah pasca shift malam","competitorAwareness":["Gacoan","Ayam Geprek","Warkop"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('dpk_001', 'depok', 'Farhan Mahendra', 19, '18-24', 'male', 'Mahasiswa UI (Teknik)', 'mid', 3500000, 1500000, '["akademis","nugas di kafe","aktif organisasi","pencinta kopi susu"]', 'Apartemen Mares, Depok', '{"priceElasticity":"sensitive","decisionFactor":["WiFi (wajib)","colokan listrik","harga murah","rasa"],"preferredChannel":["offline","GoFood"],"weeklyFnBSpend":400000}', '{"values":["prestasi","pengakuan","konektivitas"],"mediaConsumption":["Twitter/X","YouTube","LinkedIn"],"peerInfluence":"medium"}', '{"culturalNote":"Margonda Depok adalah medan perang F&B mahasiswa, harga 15rb-25rb adalah sweet spot","competitorAwareness":["Kopi Kenangan","Janji Jiwa","Warkop Kekinian","McDonalds"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('dpk_002', 'depok', 'Larasati Putri', 23, '18-24', 'female', 'Freelance Translator', 'lower-mid', 6500000, 2000000, '["introvert","cat lover","suka matcha","WFH harian"]', 'Kos area Kukusan', '{"priceElasticity":"moderate","decisionFactor":["rasa","ketenangan tempat","pilihan menu non-kopi"],"preferredChannel":["GrabFood","offline"],"weeklyFnBSpend":500000}', '{"values":["kesehatan mental","kenyamanan","kualitas"],"mediaConsumption":["Instagram","Tumblr (masih pakai)","Pinterest"],"peerInfluence":"low"}', '{"culturalNote":"Depok area Kukusan lebih tenang dibanding Margonda, cocok untuk niche market","competitorAwareness":["Kafe Niche","Teh Lokal","Home Industri"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('dpk_003', 'depok', 'Pak RT Slamet', 52, '41-55', 'male', 'Pensiunan / Pemilik Toko Kelontong', 'lower-mid', 5500000, 1000000, '["sosial warga","burung berkicau","tradisional","hemat"]', 'Perkampungan di area Beji', '{"priceElasticity":"very_sensitive","decisionFactor":["harga","rasa familiar","kedekatan dengan pemilik"],"preferredChannel":["offline","Pasar"],"weeklyFnBSpend":200000}', '{"values":["kerukunan","agama","tradisi"],"mediaConsumption":["TV","WhatsApp","Ceramah YouTube"],"peerInfluence":"high"}', '{"culturalNote":"Warga asli Depok cenderung skeptis dengan brand nasional yang terlalu ''mahal''","competitorAwareness":["Warteg","Pasar Tradisional","Pedagang Keliling"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('dpk_004', 'depok', 'Yasmine Almira', 28, '25-30', 'female', 'Creative Content Studio Manager', 'mid', 10000000, 3000000, '["ekspresif","fashionable","coffee connoisseur","aktif gym"]', 'Cluster di area Grand Depok City (GDC)', '{"priceElasticity":"moderate","decisionFactor":["brand image","kualitas produk","keunikan","kecepatan serve"],"preferredChannel":["GoFood","offline kafe estetik"],"weeklyFnBSpend":700000}', '{"values":["status","produktivitas","self-love"],"mediaConsumption":["Instagram","Twitter","Spotify Podcast"],"peerInfluence":"medium"}', '{"culturalNote":"Warga GDC Depok adalah kelas menengah yang mulai jenuh dengan Margonda","competitorAwareness":["Fore","Starbucks","Kafe Lokal GDC"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('dpk_005', 'depok', 'Indra Perkasa', 38, '31-40', 'male', 'PNS Komuter (Depok - Jakarta)', 'mid', 12000000, 3000000, '["lelah komuter","pencinta kopi sachet (pagi) & kopi beneran (weekend)","keluarga"]', 'Perumahan di area Sawangan', '{"priceElasticity":"moderate","decisionFactor":["kepraktisan","rasa","bisa buat keluarga"],"preferredChannel":["GrabFood","offline (saat weekend di mall)"],"weeklyFnBSpend":600000}', '{"values":["tanggung jawab","kenyamanan","efisiensi"],"mediaConsumption":["Berita Online","WhatsApp Group","YouTube"],"peerInfluence":"medium"}', '{"culturalNote":"Sawangan kini jadi primadona baru hunian Depok dengan market power yang kuat","competitorAwareness":["Pasar Modern","Malls di Margonda","Resto Keluarga"]}');

