-- 006: Seed personas untuk Parung
-- 5 personas representatif: Warga Lokal (60%), Pekerja Commuter (25%), Pelajar (15%)

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('prng_001', 'parung', 'Ibu Rosmini', 40, '31-40', 'female', 'Ibu Rumah Tangga / Pedagang Sayur Pasar', 'low', 3500000, 800000, '["pasar tradisional","masak sendiri","arisan warga","hemat ketat"]', 'Kampung warga Parung Bogor', '{"priceElasticity":"very_sensitive","decisionFactor":["harga murah","porsi banyak","rasa rumahan","halal"],"preferredChannel":["offline (pasar tradisional)","warung keliling"],"weeklyFnBSpend":150000}', '{"values":["keluarga","kehematan","kerukunan warga"],"mediaConsumption":["WhatsApp Group","YouTube pengajian","sinetron TV"],"peerInfluence":"high"}', '{"culturalNote":"Warga lokal Parung sangat mengandalkan pasar tradisional dan warung langganan. Loyalitas tinggi pada penjual yang sudah dikenal lama.","competitorAwareness":["Warung Nasi Sunda","Gorengan","Pedagang Keliling","Bubur Ayam"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('prng_002', 'parung', 'Hendra Saputra', 31, '25-30', 'male', 'Karyawan Swasta Komuter (Parung–Depok)', 'lower-mid', 6200000, 1400000, '["komuter harian","praktis di perjalanan","lelah pulang malam","ngopi sachet"]', 'Kontrakan di Parung dekat jalan raya', '{"priceElasticity":"sensitive","decisionFactor":["kecepatan","harga terjangkau","lokasi pinggir jalan","mengenyangkan"],"preferredChannel":["offline (warung pinggir jalan)","GoFood sesekali"],"weeklyFnBSpend":280000}', '{"values":["kepraktisan","keluarga","stabilitas ekonomi"],"mediaConsumption":["YouTube","WhatsApp","Facebook"],"peerInfluence":"medium"}', '{"culturalNote":"Pekerja komuter Parung sangat terbatas waktu. Menu murah dan cepat di pinggir jalan raya Parung adalah pilihan utama saat pergi/pulang kerja.","competitorAwareness":["Warteg","Nasi Uduk","Gorengan","Kopi Sachet"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('prng_003', 'parung', 'Dinda Aulia', 17, '13-17', 'female', 'Siswi SMA Negeri Parung', 'low', 500000, 350000, '["jajan sekolah","TikTok","nongkrong warteg dekat sekolah","hemat uang saku"]', 'Rumah orang tua di kampung Parung', '{"priceElasticity":"very_sensitive","decisionFactor":["harga 5-10rb","rasa manis/gurih","viral TikTok","beli bareng teman"],"preferredChannel":["offline (warung dekat sekolah)","jajan kaki lima"],"weeklyFnBSpend":80000}', '{"values":["pertemanan","tren sosial","hiburan ringan"],"mediaConsumption":["TikTok","Instagram","WhatsApp"],"peerInfluence":"very_high"}', '{"culturalNote":"Segmen pelajar Parung memiliki daya beli sangat terbatas. Keputusan beli sangat dipengaruhi teman. Jajanan di bawah 10rb adalah batas atas.","competitorAwareness":["Cimol","Batagor","Es Teh","Cireng","Jajanan Sekolah"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('prng_004', 'parung', 'Pak Asep', 48, '41-55', 'male', 'Pemilik Warung Makan Sunda', 'lower-mid', 5000000, 1200000, '["bangun subuh","ke pasar tiap pagi","komunitas pedagang","suka masakan Sunda otentik"]', 'Warung di pasar Parung', '{"priceElasticity":"moderate","decisionFactor":["rasa otentik Sunda","bahan lokal segar","harga bahan baku","pelanggan setia"],"preferredChannel":["offline","pasar tradisional","supplier lokal"],"weeklyFnBSpend":200000}', '{"values":["kerja keras","tradisi kuliner Sunda","kepercayaan pelanggan"],"mediaConsumption":["Radio","WhatsApp","Berita TV lokal"],"peerInfluence":"medium"}', '{"culturalNote":"UMKM kuliner Parung sangat bergantung pada bahan baku lokal dari pasar. Konsumen loyal pada rasa lalapan dan sambal otentik. Produk pendatang harus bisa bersanding dengan selera lokal.","competitorAwareness":["Nasi Liwet Sunda","Ayam Goreng Kampung","Warung Soto","Pecel Lele"]}');

INSERT OR IGNORE INTO personas (id, city_id, name, age, age_group, gender, occupation, income_level, monthly_income, monthly_disposable, lifestyle, location, shopping_behavior, psychographic, city_context)
VALUES ('prng_005', 'parung', 'Ujang Permana', 25, '18-24', 'male', 'Buruh Bangunan / Pekerja Lepas', 'low', 3800000, 900000, '["nongkrong warung","rokok","gorengan","bayar harian"]', 'Kontrakan murah area Parung', '{"priceElasticity":"very_sensitive","decisionFactor":["harga di bawah 15rb","mengenyangkan","tidak perlu jalan jauh","bisa utang/bon"],"preferredChannel":["offline (warung dekat proyek)","pedagang kaki lima"],"weeklyFnBSpend":200000}', '{"values":["solidaritas sesama pekerja","kepraktisan","makan kenyang"],"mediaConsumption":["YouTube","Facebook","TikTok sesekali"],"peerInfluence":"high"}', '{"culturalNote":"Pekerja lepas Parung adalah segmen volume tinggi dengan margin rendah. Mereka mencari tempat makan yang bisa bayar kemudian (bon/utang) dan sangat loyal jika diperlakukan baik.","competitorAwareness":["Warteg","Nasi Bungkus","Gorengan","Mie Instan Rebus"]}');
